CREATE TABLE tree (
	id int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name varchar(100) NOT NULL,
	description text NOT NULL,
	parent_id int UNSIGNED DEFAULT NULL,
	FOREIGN KEY (parent_id) REFERENCES tree (id)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARSET=UTF8;

CREATE TABLE users (
	id int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username varchar(30) NOT NULL UNIQUE KEY,
	password varchar(300) NOT NULL,
	is_admin boolean NOT NULL
) ENGINE=InnoDB CHARSET=UTF8;